# docker-compose.yml
version: "3.7"
services:
  mailserver:
    build:
      args:
        user: lachlan
        uid: 1000
      context: .
      dockerfile: ./docker/mailserver/Dockerfile.application
    container_name: mailserver
    restart: unless-stopped
    volumes:
      - ./:/home/lachlan/mail
    networks:
      - mailserver-network
    env_file: .env
    environment:
      - MAIL_USER
      - MAIL_PASSWORD
      - MAIL_HOST

networks:
  mailserver-network:
    driver: bridge
